# Generated by Django 2.2.4 on 2019-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogImage',
            field=models.ImageField(default='default.jpg', upload_to='blogImages'),
        ),
    ]
