# Generated by Django 2.2.4 on 2019-08-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.ImageField(default='default.jpg', upload_to='blogImages'),
        ),
    ]
